version: '2'

services:

  api:
    build: .
    image: dotlouis/soon
    networks:
      - apiMongo
      - apiKong
    links:
      - mongo
    restart: always
    environment:
      # reference of the container alias as hostname through the network
      # https://docs.docker.com/engine/userguide/networking/work-with-networks/
      MONGO_HOST: mongo

  mongo:
    image: mongo
    networks:
      - apiMongo
    volumes:
      - apiData:/data/db

  kong:
    image: mashape/kong
    ports:
      - "8000-8001:8000-8001"
      - "7946:7946"
      - "7946:7946/udp"
    links:
      - api
      - cassandra:kong-database
    networks:
      - apiKong
      - cassandraKong
    restart: always
    security_opt:
      - seccomp:unconfined

  cassandra:
    image: cassandra:2.2.5
    networks:
      - cassandraKong
    volumes:
      - kongData:/var/lib/cassandra

networks:
  apiMongo:
    driver: bridge
  apiKong:
    driver: bridge
  cassandraKong:
    driver: bridge

volumes:
  # Host data of kong from cassandra like apis, plugins, consumers
  kongData:
    driver: local
  # Host data of the api from mongo like events (all the important stuff)
  apiData:
    driver: local
